apiVersion: v1
kind: Service
metadata:
  name: data-collector
  labels:
    app: data-collector
  annotations:
    cloud.google.com/load-balancer-type: "internal"
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    name: data-collector
    protocol: TCP
  selector:
    app: data-collector

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-collector
  labels:
    name: data-collector
spec:
  replicas: 4
  template:
    metadata:
      labels:
        name: data-collector
        app: data-collector
    spec:
      nodeSelector:
        cloud.google.com/gke-nodepool: default-pool
      containers:
        - name: data-collector
          image: arthurmde/data-collector:0.2-0.12-exp2
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /health_check
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          readinessProbe:
            httpGet:
              path: /health_check
              port: 3000
            initialDelaySeconds: 30
            timeoutSeconds: 30
          env:
            - name: RAILS_MAX_THREADS
              value: '25'
            - name: MONGO_USER
              value: 'admin'
            - name: MONGO_PASSWORD
              value: 'admin'
            - name: MONGO_HOSTS
              value: "'mongo-0.mongo:27017','mongo-1.mongo:27017','mongo-2.mongo:27017','mongo-3.mongo:27017'"
            - name: MONGO_POOL_SIZE
              value: '25'
            - name: MONGO_REPLICA_SET
              value: 'rs0'
            - name: RABBITMQ_HOST
              value: 'rabbitmq'
            - name: KONG_URI
              value: 'http://kong-admin:8001'
            - name: REGISTER_METHOD
              value: 'api'
            - name: MY_POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          command: [ "/bin/sh", "-c", "apt install curl -y && export SELF_HOST=data-collector:3000 && bundle exec rails s -p 3000 -b 0.0.0.0" ]
          resources:
            requests:
              memory: "200M"
              cpu: "0.2"
